// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQF-6LFdReOnyfJods6r7K6N5V872EDS8',
    appId: '1:239862975990:android:ec40e6c64e0c05d1bbcbd7',
    messagingSenderId: '239862975990',
    projectId: 'booknglow-1',
    storageBucket: 'booknglow-1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRP-UAMT_arsRrvAkES4bxJeRHdqOT6Xo',
    appId: '1:239862975990:ios:86bf4f2dc6486967bbcbd7',
    messagingSenderId: '239862975990',
    projectId: 'booknglow-1',
    storageBucket: 'booknglow-1.firebasestorage.app',
    iosBundleId: 'com.example.booknglow',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATs8vLWx5kN-7woxwX0FB6bcxdhmtoaTE',
    appId: '1:239862975990:web:4a5560a891466c00bbcbd7',
    messagingSenderId: '239862975990',
    projectId: 'booknglow-1',
    authDomain: 'booknglow-1.firebaseapp.com',
    storageBucket: 'booknglow-1.firebasestorage.app',
  );
}
